lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config

nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Chris Wyatt
  description: A pipeline for Genome Wide Association Studies
  force: false
  is_nfcore: true
  name: gwas
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0dev
